[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "https://laxy.travel"
  status = 301
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/laxy-admin/*"
  to = "/laxy-admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context]
  [context.production.environment]
    # Add any production-only environment variables here if needed
    # Example: NODE_ENV = "production"
